#!/usr/bin/env python
# This file is part of ts_aos_ai.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
"""Regenerate the model manifests from the model files on disk.

This walks the model directories, computes a SHA-256 digest and byte size for
every model file, and writes:

* ``models.yaml`` at the repo root -- a manifest of the current model files
  (the tree only ever holds the current version; the version archive is git
  history and tags).
* ``model_history.yaml`` at the repo root -- an append-only ledger mapping
  content hash to model version, for tracing on-sky runs (see README.md).

Hashes are always generated from the file bytes, never hand-typed. Every
model's hash is printed so it can be pasted into the donut_viz pipeline YAMLs
(AiDonut ``estimateZernikes.modelSha256``; TARTS ``wavenetSha256`` /
``alignetSha256`` / ``aggregatornetSha256`` / ``oodModelSha256``).

Run it after adding or replacing a model file (see README.md for the full
per-bump workflow).
"""

import argparse
import datetime
import hashlib
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
AI_DONUT_MODEL_DIR = REPO_ROOT / "ai_donut" / "model"
TARTS_MODEL_DIR = REPO_ROOT / "tarts" / "model"

# File patterns treated as model weights in each area.
AI_DONUT_PATTERNS = ("*.pt",)
TARTS_PATTERNS = ("*.ckpt", "*.joblib")

AUTOGEN_HEADER = "# AUTO-GENERATED by scripts/update_manifests.py -- do not edit by hand.\n"

# Append-only ledger mapping content hash -> model identity, so a SHA-256 seen
# in butler provenance from an on-sky run can be traced to the model version
# that produced it -- even after that version has left the working tree.
MODEL_HISTORY_PATH = REPO_ROOT / "model_history.yaml"
HISTORY_HEADER = (
    "# APPEND-ONLY ledger: model content hash (sha256) -> model identity/version.\n"
    "# Maintained by scripts/update_manifests.py; entries are only ever added,\n"
    "# never removed. Use it to trace a hash recorded in butler provenance back\n"
    "# to the model version that produced it. The 'notes' field is free for\n"
    "# manual annotation (e.g. the git tag a version shipped under).\n"
)


def sha256(path: Path, chunk_size: int = 1 << 20) -> str:
    """Return the SHA-256 hex digest of a file, streamed in chunks."""
    hasher = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk_size), b""):
            hasher.update(block)
    return hasher.hexdigest()


def find_files(directory: Path, patterns: tuple[str, ...]) -> list[Path]:
    """Return a sorted list of files in ``directory`` matching ``patterns``."""
    matches: list[Path] = []
    for pattern in patterns:
        matches.extend(directory.glob(pattern))
    return sorted(set(matches))


def entry_for(path: Path) -> dict:
    """Build a manifest entry (repo-relative path, sha256, size) for a file."""
    return {
        "path": str(path.relative_to(REPO_ROOT)),
        "sha256": sha256(path),
        "size": path.stat().st_size,
    }


def build_manifest() -> dict:
    """Build the ``models.yaml`` structure from the files currently on disk."""
    manifest: dict = {
        "generated": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "ai_donut": {},
        "tarts": {},
    }

    if AI_DONUT_MODEL_DIR.is_dir():
        for path in find_files(AI_DONUT_MODEL_DIR, AI_DONUT_PATTERNS):
            manifest["ai_donut"][path.name] = entry_for(path)

    if TARTS_MODEL_DIR.is_dir():
        for version_dir in sorted(p for p in TARTS_MODEL_DIR.iterdir() if p.is_dir()):
            entries = {
                path.name: entry_for(path)
                for path in find_files(version_dir, TARTS_PATTERNS)
            }
            if entries:
                manifest["tarts"][version_dir.name] = entries

    return manifest


def write_yaml(path: Path, data: dict) -> None:
    """Write ``data`` to ``path`` as YAML with the auto-generated header."""
    with open(path, "w") as f:
        f.write(AUTOGEN_HEADER)
        yaml.safe_dump(data, f, sort_keys=True, default_flow_style=False)


def iter_manifest_files(manifest: dict):
    """Yield ``(method, version, filename, entry)`` for every model file.

    The ``version`` is the label used to identify the model in the history
    ledger: for TARTS it is the version directory name (e.g. ``v4``); for
    AIDonut it is the filename stem, which encodes version and date
    (e.g. ``aidonut_unbinned_v1_20260903``).
    """
    for filename, entry in manifest["ai_donut"].items():
        yield "ai_donut", Path(filename).stem, filename, entry
    for version, entries in manifest["tarts"].items():
        for filename, entry in entries.items():
            yield "tarts", version, filename, entry


def update_history(manifest: dict) -> int:
    """Merge the current file hashes into the append-only model_history.yaml.

    Existing entries are never modified or removed, so hashes from retired
    model versions remain traceable. Returns the number of entries added.
    """
    history: dict = {}
    if MODEL_HISTORY_PATH.is_file():
        with open(MODEL_HISTORY_PATH) as f:
            history = yaml.safe_load(f) or {}

    today = datetime.date.today().isoformat()
    added = 0
    for method, version, filename, entry in iter_manifest_files(manifest):
        digest = entry["sha256"]
        if digest in history:
            continue
        history[digest] = {
            "method": method,
            "version": version,
            "file": filename,
            "path": entry["path"],
            "size": entry["size"],
            "first_recorded": today,
            "notes": "",
        }
        added += 1

    with open(MODEL_HISTORY_PATH, "w") as f:
        f.write(HISTORY_HEADER)
        yaml.safe_dump(history, f, sort_keys=True, default_flow_style=False)
    return added


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()

    manifest = build_manifest()

    models_yaml = REPO_ROOT / "models.yaml"
    write_yaml(models_yaml, manifest)
    print(f"Wrote {models_yaml.relative_to(REPO_ROOT)}")

    added = update_history(manifest)
    print(
        f"Updated {MODEL_HISTORY_PATH.relative_to(REPO_ROOT)} "
        f"({added} new entr{'y' if added == 1 else 'ies'})"
    )

    if manifest["ai_donut"]:
        print("\nAiDonut hashes (paste into donut_viz estimateZernikes.modelSha256):")
        for name, entry in manifest["ai_donut"].items():
            print(f"  {name}: {entry['sha256']}")

    for version, entries in manifest["tarts"].items():
        print(f"\nTARTS {version} hashes (paste into the matching *Sha256 configs):")
        for name, entry in entries.items():
            print(f"  {name}: {entry['sha256']}")


if __name__ == "__main__":
    main()
